### PR TITLE
Fix a typo in comment

### PR DESCRIPTION
**Pull request by gy741**
Hello.

I corrected the typos.

Thanks.

Changes:

```
doc/TUTORIAL.md:1: runing -> "running"
```

### CODE REVIEW

**Comment by junbeomlee** [comment]
Thank you for your first Pull request. I had a typos to make it hastily, but I think it would be better to just use the title as a `Tutorial`. Could you fix that?(use `git add . && git commit --amend` after change title!!)
Please sign clahub!!
Thank you!

**Comment by gy741** [comment]
@junbeomlee 

Hello.

Thank you for your quick answer.

>I think it would be better to just use the title as a "Tutorial".

Do you mean the "Commit title" ?
for exmpale:
Commit title : Fix Tutorial

>Please sign clahub!!

Okay. I signed

Thanks.

**Comment by junbeomlee** [comment]
No i mean "install and running tutorial" to just "Tutorial"

2018년 8월 28일 (화) 오후 2:24, gy741 <notifications@github.com>님이 작성:

**Comment by gy741** [comment]
@junbeomlee 

Aha, I modified it.
Please check.

**Pull request merged**
