### PR TITLE
Added pr template

### LINKED ISSUE #732: [Doc] PULL_REQUEST_TEMPLATE 위치 수정
**Componet**
Doc

**Proposal Detail**
relocate PULL_REQUEST_TEMPLATE.md file to engine/.github

### PR DESCRIPTION
**Pull request by sahitpj**
resolved: #732

details:

- Adds PR template

### CODE REVIEW

**Comment by junbeomlee** [comment]
Thank you for your first pull request. Please sign clahub!!

**Comment by sahitpj** [comment]
Have Signed Clahub !

**Comment by junbeomlee** [comment]
@sahitpj 
Thank you for signing.
But could you fix the commit with rebase instead of merge?
We are doing rebase instead of merge.
We want only `Added pr template` commit.
:)

**Comment by junbeomlee** [comment]
I am sorry to hear that, but the issue #732 is to move the pull request template file under the .github folder !! Pull request template already exists.(engine/PULL_REQUEST_TEMPLATE.md)

Could you close this pull request and update the latest brunch with `git pull -r upstream develop`, modify the template location and open new pull request?(Please update your brunch with rebase! no just merge)

**Pull request closed without merging**
